version: '3.3'

services:

  front:
    image: node
    # restart: always
    working_dir: /home/node/front
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - eagle-network
    volumes:
      - ./:/home/node/front
    command: sh -c "yarn && yarn build"

networks:
  eagle-network:
   