version: '3.3'

services:

  front:
    image: node
    # restart: always
    working_dir: /home/node/front
    ports:
      - 80:3000
    networks:
      - petzeira-network
    volumes:
      - ./:/home/node/front
    command: sh -c "yarn && yarn build"

networks:
  petzeira-network:
   